"use client"

import { useState } from "react"
import { Shell } from "@/components/layout/Shell"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Loader2, BrainCircuit } from "lucide-react"
import { QuizPlayer } from "@/components/quiz/QuizPlayer"
import { toast } from "sonner"

export default function QuizPage() {
    const [loading, setLoading] = useState(false)
    const [activeQuiz, setActiveQuiz] = useState<any>(null)
    const [formData, setFormData] = useState({
        topic: "",
        difficulty: "BEGINNER",
    })

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)

        try {
            const res = await fetch("/api/quizzes/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(formData),
            })

            if (!res.ok) throw new Error("Failed to generate quiz")

            const quiz = await res.json()
            setActiveQuiz(quiz)
            toast.success("Quiz generated! Good luck!")
        } catch (error) {
            toast.error("Failed to generate quiz. Please try again.")
        } finally {
            setLoading(false)
        }
    }

    return (
        <Shell>
            <div className="max-w-4xl mx-auto space-y-8">
                {!activeQuiz ? (
                    <>
                        <div className="text-center space-y-4">
                            <h1 className="text-4xl font-bold tracking-tight">AI Quiz Generator</h1>
                            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                                Test your knowledge with personalized quizzes generated by AI.
                                Choose a topic and difficulty level to get started.
                            </p>
                        </div>

                        <Card className="max-w-md mx-auto">
                            <CardHeader>
                                <CardTitle>Create New Quiz</CardTitle>
                                <CardDescription>
                                    Enter a topic to generate 5 multiple-choice questions.
                                </CardDescription>
                            </CardHeader>
                            <CardContent>
                                <form onSubmit={handleGenerate} className="space-y-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="topic">Topic</Label>
                                        <Input
                                            id="topic"
                                            placeholder="e.g., React Hooks, SQL Joins, Python Basics"
                                            value={formData.topic}
                                            onChange={(e) => setFormData({ ...formData, topic: e.target.value })}
                                            required
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="difficulty">Difficulty</Label>
                                        <Select
                                            value={formData.difficulty}
                                            onValueChange={(value) => setFormData({ ...formData, difficulty: value })}
                                        >
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select difficulty" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="BEGINNER">Beginner</SelectItem>
                                                <SelectItem value="INTERMEDIATE">Intermediate</SelectItem>
                                                <SelectItem value="ADVANCED">Advanced</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <Button type="submit" className="w-full" disabled={loading}>
                                        {loading ? (
                                            <>
                                                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                                Generating Questions...
                                            </>
                                        ) : (
                                            <>
                                                <BrainCircuit className="mr-2 h-4 w-4" />
                                                Start Quiz
                                            </>
                                        )}
                                    </Button>
                                </form>
                            </CardContent>
                        </Card>
                    </>
                ) : (
                    <div className="space-y-6">
                        <Button
                            variant="ghost"
                            onClick={() => setActiveQuiz(null)}
                            className="mb-4"
                        >
                            ← Back to Generator
                        </Button>
                        <QuizPlayer quiz={activeQuiz} />
                    </div>
                )}
            </div>
        </Shell>
    )
}
